Import numpy:

In [71]:
import numpy as np

In [72]:
#scenerio 1
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

a1,a2

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [73]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [74]:
#scenerio 2
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)

a3,a4

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2]]))

In [75]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

Broad Casting:
The term broadcasting refers to the ability of numpy to treat arrays of different shapes during arithmetic operations.Arithmetic operations on arrays are usually done on corresponding elements.If two arrays are exactly same shape, it perform these operations smoothly.

And if the dimension of these arrays are dissimiler, element to element operation not possible. Operations on arrays of non similer shapes is still possible in Numpy, because the capability of broadcasting.The smaller array is broadcast to the largest array so that they have compatible shapes.

Rules for broadcastoing:

In [76]:
# if x=m and y=n operation will take
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

a1,a2

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [77]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [78]:
# if x=1 and y=n then also operation will take place (same dimension)
# if we 1 from all values of reshape thwn we need to check that corresponding value and corresponding value from other array is same then boradcasting will apply
a5=np.arange(3).reshape(1,3)
a6=np.arange(12).reshape(4,3)

a5,a6

(array([[0, 1, 2]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [79]:
a5+a6


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [80]:
a7=np.arange(4).reshape(1,4)
a8=np.arange(12).reshape(3,4)

a7,a8

(array([[0, 1, 2, 3]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [81]:
a7+a8

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [82]:
# if x=1 and y!=n then also operation will not take place
# if we 1 from all values of reshape then we need to check that corresponding value and corresponding value from other array is same then boradcasting will apply if not then broadcasting will not appy
a9=np.arange(5).reshape(1,5)
a10=np.arange(10).reshape(5,2)

a9,a10

(array([[0, 1, 2, 3, 4]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [83]:
#a9+a10

In [84]:
# if x=1 and n=1 then y==m operation to take place.
# # if we 1 from all values of reshape and 1 from corresponding of other array then we need to check that other value of reshape of array1 is similer to other value of array2. it yes then broad casting will apply
arr11=np.arange(4).reshape(1,4)
arr12=np.arange(4,8).reshape(4,1)

arr11,arr12

(array([[0, 1, 2, 3]]),
 array([[4],
        [5],
        [6],
        [7]]))

In [85]:
arr11+arr12

array([[ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [86]:
# if x=1 and y=1 then the operation will take place no matter that
# if both values of reshape of an array (1,1) is 1 then there is any value in reshape in other array it does not matter broadcasting will aply.
arr13=np.arange(1).reshape(1,1)
arr14=np.arange(20).reshape(4,5)

arr13,arr14

(array([[0]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]))

In [87]:
arr13+arr14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])