Import Library

In [1]:
import numpy as np

Make a numpy array with np.array()

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

Check type of array

In [3]:
type(arr1)

numpy.ndarray

Check shape of an array.

In [5]:
arr1.shape

(5,)

Make a 2D list with numpy

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

Make array of 0

In [8]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

Make array of 1

In [10]:
arr4=np.ones((2,2))
arr4

array([[1., 1.],
       [1., 1.]])

Make an identity matrix

In [11]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Make an array for a sequence of numbers

In [14]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr7=np.arange(10,20,2)
arr7

array([10, 12, 14, 16, 18])

Make an array with linspace() we give them start and stop number and give an count of numbers hpw many we need?

In [20]:
arr8=np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

Make an arry with .copy()

In [21]:
arr9=arr8.copy()
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])