Import numpy

In [9]:
import numpy as np

In [10]:
arr1=np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Fancy Indexing: we use it when we need to pick or catch some of the rows like discontinuous (0,2,5,8) the we use fancy indexing.

In [11]:
arr1[[1,5]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23]])

In [12]:
arr1[[4,1]]

array([[16, 17, 18, 19],
       [ 4,  5,  6,  7]])

In [13]:
arr1[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])