In [1]:
import numpy as np

Make a 2D list

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1.shape

(2, 3)

Check the dimension of an array with ndim.

In [4]:
arr1.ndim

2

Chech the size of an array.

In [5]:
arr1.size

6

Make a 3D list and check his shape

In [8]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,5,8]]])
print(arr2)
arr2.shape

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 5 8]]]


(2, 2, 3)

It returns the dimension of an array.

In [9]:
arr2.ndim

3

it returns the size of an array. Number of elements in an array.

In [10]:
arr2.size

12

n NumPy, itemsize is another attribute of an ndarray (n-dimensional array). It represents the size in bytes of each element in the array.

In [11]:
arr2.itemsize

4

It returns the type of an array.

In [12]:
arr2.dtype

dtype('int32')

The astype() method in NumPy is used to cast an array to a specified data type. It creates a new array with the specified data type, while preserving the data in the original array as much as possible by performing any necessary conversions.

In [14]:
print(arr2)
arr2.astype('float')

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 5 8]]]


array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[7., 8., 9.],
        [1., 5., 8.]]])