Import numpy

In [24]:
import numpy as np

Make an array

In [25]:
arr1=np.random.randint(low=1,high=100,size=30).reshape(6,5)
arr1

array([[22, 40,  7, 84, 20],
       [88, 24,  3, 70, 51],
       [99, 30, 21, 53, 98],
       [41, 69, 88, 44, 65],
       [94, 60, 99, 36, 55],
       [39,  5, 42, 70, 50]])

In [26]:
arr1[0]

array([22, 40,  7, 84, 20])

In [27]:
arr1[0,0]

22

Indexing with boolean array:

In [28]:
arr1>50

array([[False, False, False,  True, False],
       [ True, False, False,  True,  True],
       [ True, False, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True, False,  True],
       [False, False, False,  True, False]])

In [29]:
#indexing using boolean array
arr1[arr1>50]

array([84, 88, 70, 51, 99, 53, 98, 69, 88, 65, 94, 60, 99, 55, 70])

In [30]:
arr1[arr1<45]

array([22, 40,  7, 20, 24,  3, 30, 21, 41, 44, 36, 39,  5, 42])

In [31]:
arr1[(arr1>50)&(arr1%2!=0)]

array([51, 99, 53, 69, 65, 99, 55])

In [32]:
arr1[(arr1>50)&(arr1%2!=0)]=5

In [33]:
arr1

array([[22, 40,  7, 84, 20],
       [88, 24,  3, 70,  5],
       [ 5, 30, 21,  5, 98],
       [41,  5, 88, 44,  5],
       [94, 60,  5, 36,  5],
       [39,  5, 42, 70, 50]])