Import numpy

In [1]:
import numpy as np

Make an array:

In [2]:
arr1=np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
#arr1.reshape(6,4)

In [4]:
arr2=np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

Indexing:

In [5]:
arr2[2]

3

In [6]:
arr2[-1]

5

In [7]:
arr1[2]

array([ 8,  9, 10, 11])

Slicing:

In [8]:
arr2[2:4]

array([3, 4])

In [9]:
arr1[1:2]

array([[4, 5, 6, 7]])

In [10]:
arr1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [12]:
arr1[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [13]:
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [14]:
arr1[4:6,2:4]

array([[18, 19],
       [22, 23]])

Iteration:

In [15]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [16]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [17]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,5,8]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 5, 8]]])

In [18]:
for i in arr3:
    print(i)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [2 5 8]]


In [19]:
for i in np.nditer(arr3):
    print(i)

1
2
3
4
5
6
7
8
9
2
5
8


In [20]:
arr3[1,1,2]

8

Slicing:

In [21]:
arr3[0:2,0:2,0:2]

array([[[1, 2],
        [4, 5]],

       [[7, 8],
        [2, 5]]])