Import Numpy

In [53]:
import numpy as np

Declare 2 arrays.

In [54]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

Subtract 2 Arrays.

In [55]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

Add 2 arrays.

In [56]:
arr1+arr2

array([ 5,  7,  9, 11, 13, 15])

Multiply 2 arrays.

In [57]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

Divide  2 arrays.

In [58]:
arr1/arr2

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

Mulitply an array with numner.

In [59]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

Square of an array.

In [60]:
arr1**2

array([ 1,  4,  9, 16, 25, 36])

Apply an condition on array and its give True false according to every number in an array.

In [61]:
arr1>3

array([False, False, False,  True,  True,  True])

Reshape an array. 

In [62]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)
print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


Dot product of 2 arrays.

In [63]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

Find maximum from the array.

In [64]:
arr4.max()

11

Find minimum from the array.

In [65]:
arr4.min()

6

Find minumun from all columns.

In [66]:
arr4.min(axis=0)

array([6, 7])

Find minimum from rows.

In [67]:
arr4.min(axis=1)

array([ 6,  8, 10])

Find sum of an array.

In [68]:
arr4.sum()

51

Find sum of columns.

In [69]:
arr4.sum(axis=0)

array([24, 27])

Find sum of rows.

In [70]:
arr4.sum(axis=1)

array([13, 17, 21])

Find average (mean) of an array.

In [71]:
arr4.mean()

8.5

Find mean of columns.

In [72]:
arr4.mean(axis=0)

array([8., 9.])

Find mean of roes.

In [73]:
arr4.mean(axis=1)

array([ 6.5,  8.5, 10.5])

Find standard deviation of an array.

In [74]:
arr4.std()

1.707825127659933

Find standard deviation of columns.

In [75]:
arr4.std(axis=0)

array([1.63299316, 1.63299316])

Find the standard deviation of rows.

In [76]:
arr4.std(axis=1)

array([0.5, 0.5, 0.5])

Find sin (trignometry) of an array.

In [77]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

Find median of an array.

In [78]:
np.median(arr4)

8.5

Find Exponential of an array.

In [79]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])