Import Numpy

In [1]:
import numpy as np

Ravel function:
It convert Higher dimension to 1-D array.

In [8]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
arr1.ndim

2

In [10]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6])

Reshape Function:

In [12]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Transpose Funtion:

It converts rows into column & columns itno rows.

In [16]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
arr1.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [20]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Stacking:
hstack: It stack 2 arrays horizontely.

In [24]:
arr3=np.array([[9,8,7],[6,5,4],[3,2,1]])
arr3, arr2

(array([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [26]:
np.hstack((arr2,arr3))

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4],
       [7, 8, 9, 3, 2, 1]])

vstack: it combine 2 arrays in vertically.

In [27]:
np.vstack((arr2,arr3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Splitting:

vsplit: it split an array in differnet parts in vertically.

In [36]:
np.vsplit(arr2,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

hsplit: it split an array in different parts in horizontely.

In [40]:
np.hsplit(arr2,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]