Import numpy

In [1]:
import numpy as np

Random Module

Import a random number and when when we run it it gives an new value

In [5]:
np.random.random()

0.4468445902472037

It gives same value ho many time we run it

In [10]:
np.random.seed(1)
np.random.random()

0.417022004702574

It generates random value from a given range

In [14]:
np.random.uniform(3,10)

4.027291235719791

It generates random values from the rage of numbers and for a given size

In [15]:
np.random.uniform(1,100,10)

array([10.14152088, 19.43976093, 35.21051198, 40.27997995, 54.34285667,
       42.50025693, 68.83673054, 21.24077272, 87.9336262 ,  3.71137173])

We also reshape it.

In [17]:
np.random.uniform(1,100,10).reshape(5,2)

array([[89.56605969,  9.41937693],
       [ 4.86642354, 17.81321154],
       [87.93610784, 10.73633655],
       [42.68965488, 95.83106348],
       [53.78336321, 69.49583428]])

It genrates an integer random number.

In [21]:
np.random.randint(1,10)

4

It generates random integer number for a given size.


In [22]:
np.random.randint(1,10,6)

array([3, 1, 5, 3, 8, 8])

We also reshape it into different dimensions

In [23]:
np.random.randint(1,10,6).reshape(2,3)

array([[9, 7, 4],
       [8, 8, 5]])

In [26]:
arr1=np.random.randint(1,10,6)

Find maximum 

In [27]:
arr1.max()

9

Find minimum

In [28]:
arr1.min()

1

It returns the index of maximum value.

In [29]:
np.argmax(arr1)

3

It returns the index of minimum value.

In [30]:
np.argmin(arr1)

4

Apply condition the replace odds number with -1.

In [31]:
arr1[arr1%2!=0]=-1

In [32]:
arr1

array([ 6,  4, -1, -1, -1, -1])

In [39]:
arr2=np.random.randint(1,10,6)
arr2

array([6, 8, 9, 5, 5, 8])

Apply where built in function which apply condition on array and we give value for condition true and also give value for condition false.

In [44]:
b=np.where((arr2%2!=0),-1,5)
b

array([ 5,  5, -1, -1, -1,  5])

In [45]:
c=np.where((arr2%2!=0),-1,arr2)
c

array([ 6,  8, -1, -1, -1,  8])

In [47]:
arr3=np.random.randint(1,50,15)
arr3

array([33, 13,  2, 31, 42, 25, 19, 34,  3, 45, 29, 40, 35, 11, 33])

Sort an array.

In [48]:
np.sort(arr3)

array([ 2,  3, 11, 13, 19, 25, 29, 31, 33, 33, 34, 35, 40, 42, 45])

Percentile:

In [49]:
np.percentile(arr3,25)

16.0

In [50]:
np.percentile(arr3,50)

31.0